FileVersion = 1

[Project]
Name = "Ultralight"
TargetType = "BeefLib"
StartupObject = "Program"

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/sdk/lib/Ultralight.lib", "$(ProjectDir)/dist/sdk/lib/UltralightCore.lib", "$(ProjectDir)/dist/sdk/lib/WebCore.lib", "$(ProjectDir)/dist/sdk/lib/AppCore.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/sdk/bin/*.dll\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/sdk/lib/Ultralight.lib", "$(ProjectDir)/dist/sdk/lib/UltralightCore.lib", "$(ProjectDir)/dist/sdk/lib/WebCore.lib", "$(ProjectDir)/dist/sdk/lib/AppCore.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/sdk/bin/*.dll\")"]

[Configs.Debug.Linux64]
LibPaths = ["$(ProjectDir)/dist/sdk/bin/libUltralight.so", "$(ProjectDir)/dist/sdk/bin/libUltralightCore.so", "$(ProjectDir)/dist/sdk/bin/libWebCore.so", "$(ProjectDir)/dist/sdk/bin/libAppCore.so"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/sdk/bin/*.so\")"]

[Configs.Release.Linux64]
LibPaths = ["$(ProjectDir)/dist/sdk/bin/libUltralight.so", "$(ProjectDir)/dist/sdk/bin/libUltralightCore.so", "$(ProjectDir)/dist/sdk/bin/libWebCore.so", "$(ProjectDir)/dist/sdk/bin/libAppCore.so"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/sdk/bin/*.so\")"]
